List<String> usStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

// List<String> countries = [
//   'United States',
//   'Canada',
//   'United Kingdom',
//   'Australia',
//   'India',
//   'Germany',
//   'France',
//   'Brazil',
//   'China',
//   'Japan',
//   'South Korea',
//   'Mexico',
//   'Russia',
//   'South Africa',
//   'Nigeria',
//   'Saudi Arabia',
//   'United Arab Emirates',
//   'Turkey',
//   'Egypt',
//   'Argentina',
//   'Chile',
//   'Colombia',
//   'New Zealand',
//   'Norway',
//   'Sweden',
//   'Switzerland',
//   'Italy',
//   'Spain',
//   'Portugal',
//   'Greece'
//   // Add more countries as needed
// ];
